add bookmark/profile page
marte1337/quiz-app pull request #3
Opened 2023-03-06 16:31 UTC by marte1337

2023-03-06 17:26 UTC, marte1337 commented
Probleme bereitet mir noch die Zentrierung der beiden "Counter"-Elemente auf der Profile-Page. Ich glaube, das hängt irgendwie mit dem List-Style zusammen. Vielleicht kann mir da jemand helfen?

2023-03-07 11:57 UTC, gitboej requested changes
i made some comments on minor issues, otherwise it looks pretty good :)
- Lars

2023-03-07 11:57 UTC, gitboej commented on bookmarks.html
> +    </nav>
my suggestion would be to define those icons in the footer of the webpage, but your solution looks fine as well

2023-03-07 11:57 UTC, gitboej commented on styles.css
> +
too much blank space

2023-03-07 16:00 UTC, closed without merging